In [19]:
import numpy as np

Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей [[-1, -6], [2, 6]]

In [20]:
a = np.array([[-1, -6], [2, 6]])
b, c = np.linalg.eig(a)

In [21]:
b

array([2., 3.])

In [22]:
c

array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])

Дан оператор поворота на 180 градусов, задаваемый матрицей [[-1, 0], [0, -1]]. Показать, что любой вектор является для него собственным.

In [23]:
a = np.array([[-1, 0], [0, -1]])
b, c = np.linalg.eig(a)

In [24]:
b

array([-1., -1.])

In [25]:
c

array([[1., 0.],
       [0., 1.]])

Пусть линейный оператор задан матрицей [[1, 1], [-1, 3]] . Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [26]:
a = np.array([[1, 1], [-1, 3]])
b, c = np.linalg.eig(a)

In [27]:
b

array([2.00000002, 1.99999998])

In [28]:
c

array([[ 0.70710677, -0.70710679],
       [ 0.70710679, -0.70710677]])

Пусть линейный оператор задан матрицей [[0, 3, 0], [3, 0, 0], [0, 0, 3]] . Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [29]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
b, c = np.linalg.eig(a)

In [30]:
b

array([ 3., -3.,  3.])

In [31]:
c

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])