Найти с помощью NumPy SVD для матрицы

In [1]:
import numpy as np

A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])


In [2]:
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [3]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [5]:
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [6]:
V

array([[ 0.07116451, -0.36737824, -0.92734505],
       [ 0.71702467,  0.66514082, -0.20847855],
       [ 0.69340553, -0.65009301,  0.31075368]])

In [7]:
W

array([[ 0.07116451,  0.71702467,  0.69340553],
       [-0.36737824,  0.66514082, -0.65009301],
       [-0.92734505, -0.20847855,  0.31075368]])

Для матрицы из предыдущего задания найти:

а) евклидову норму;

б) норму Фробениуса.