1. Найти скалярное произведение векторов  x,y∈R :

а)  x=(0,−3,6), y=(−4,7,9); 

б)  x=(7,−4,0,1), y=(−3,1,11,2). 

In [8]:
0 * (-4) + (-3) * 7 + 6 * 9

33

In [9]:
7 * (-3) + (-4) * 1 + 0 * 11 + 1 * 2 

-23

2. Найти нормы векторов  (4,2,4)  и  (12,3,4)  и угол между ними.


In [10]:
import math

In [11]:
math.sqrt((4 ** 2) + (2 ** 2) + (4 ** 2))

6.0

In [12]:
math.sqrt((12 ** 2) + (3 ** 2) + (4 ** 2))

13.0

In [13]:
4 * 12 + 2 * 3 + 4 * 4

70

In [14]:
70 / (6 * 13)

0.8974358974358975

3. Будет ли линейное пространство евклидовым, если за скалярное произведение принять:

а) произведение длин векторов;

б) утроенное обычное скалярное произведение векторов?

**Ответ:** a) является евклидовым

б) не является евклидовым

4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве  R3 :

а)  (1,0,0),(0,0,1); 

б)  (1/2–√,−1/2–√,0),(1/2–√,1/2–√,0),(0,0,1); 

в)  (1/2,−1/2,0),(0,1/2,1/2),(0,0,1); 

г)  (1,0,0),(0,1,0),(0,0,1)?

**Ответ:** г) 

1. Исследовать на линейную зависимость:

f1(x)=ex, f2(x)=1, f3(x)=x+1, f4(x)=x−ex. 

**Ответ:** f4(x)=f3(x) - f2(x) - f1(x) => x + 1 - 1 - ex = х - ex 

то есть вектор  f4(x)  — линейная комбинация векторов f1(x), f2(x) и f3(x), из чего можно сделать вывод, что они линейно зависимы.

2. Исследовать на линейную зависимость:

f1(x)=2, f2(x)=x, f3(x)=x2, f4(x)=(x+1)2

**Ответ:** f4(x)=f3(x) + 2f2(x) +  0,5f1(x) => x2 + 2х + 0,5 * 2 = (x+1)2 

то есть вектор  f4(x)  — линейная комбинация векторов f1(x), f2(x) и f3(x), из чего можно сделать вывод, что они линейно зависимы.

3. Найти координаты вектора x=(2,3,5)∈R3 в базисе b1=(0,0,10), b2=(2,0,0), b3=(0,1,0).


**Ответ:** 

x = (2,3,5) = 2⋅(2,0,0)+3⋅(0,1,0)+5⋅(0,0,10)= 1⋅(1,0,0)+3⋅(0,1,0)+0,5⋅(0,0,1)

то есть координатами вектора  x  являются  1 , 3, 0,5.

In [15]:
import numpy as np


b1 = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 10]])
v = np.array([2, 3, 5])

print(np.linalg.solve(b1, v))

[1.  3.  0.5]


4. Найти координаты вектора 3x2−2x+2∈R3[x]:

а) в базисе 1, x, x2;

б) в базисе x2, x−1, 1.

In [16]:
b1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
b2 = np.array([[1, 0, 0], [0, 1, -1], [0, 0, 1]])
v = np.array([2, -2, 3])

print(np.linalg.solve(b1, v))
print(np.linalg.solve(b2, v))

[ 2. -2.  3.]
[2. 1. 3.]


5. Установить, является ли линейным подпространством:
    
а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

б) все векторы, являющиеся линейными комбинациями данных векторов  {u1,u2,…,un} .

a)  не является линейным подпространством.

б) Согл. определению, если взять в n-мерном линейном пространстве конечный набор векторов {u1,u2,…,un}. Тогда совокупность образует некоторое подпространство. Т.о. является линейным подпространством.